### ISSUE TITLE
似乎有些问题

### ISSUE THREAD

**Issue by xiaozixun** [knowlet/Gentle-Viewer#1]
如果画集内的图片很多，就会出现一部分无法观看。
此外，图片显示位置有点歪（如果放大浏览器字体或缩放的话）

**Comment by knowlet** [comment]
超過 200+ pic 的漫畫如果一次載入後面好像會被擋掉，解決方法是點頁數讓他從指定頁數再往後載入（不過原本沒有這個設計，所以會計算錯誤，看到一些 Loading 的圖示）應該就可以了。

以後有空可能考慮加一個動態載入的功能來修正這個問題。

圖片顯示並沒有更動原本的 CSS，原本就是靠左對齊，請問你縮放造成顯示位置有點歪是怎麼個歪法？

**Comment by xiaozixun** [comment]
@knowlet 歪到右边去了，没有居中显示。
图片外链：http://chuantu.biz/t6/238/1519645945x-1566638279.png （不知能否看到）
（我实在是不大会用github）
