### ISSUE TITLE
EX上排版似乎有問題

### ISSUE THREAD

**Issue by lyj222382** [knowlet/Gentle-Viewer#2]
EX上打開頁面圖片全部加載，疊在一起。
<img width="1920" alt="錯位" src="https://github.com/user-attachments/assets/c9d7a3a2-ddbc-453e-96b6-c276bde722e3">

**Comment by knowlet** [comment]
請更新到 1.0 版本

**Comment by lyj222382** [comment]
> 请更新到 1.0 版本

已經是1.0版本，EX上排版就這樣。感覺是EX上所有圖片同一時刻加載層疊在一起，ehentai上打開反而沒有問題。我的瀏覽器是chrome，win7系統，篡改猴也是新版本。

**Comment by knowlet** [comment]
@lyj222382 我剛在 chrome + ex 上面測試也都正常
![image](https://github.com/user-attachments/assets/8a22a313-47fb-4770-9ac5-308d63c72c31)
可以幫我重新安裝腳本試試看嗎，可能是之前推錯的一個版本你剛好更新到了，或者幫我檢查腳本裡面是不是沒有這一行程式碼
```
window.gdt.classList.remove("gt100");
```
如果有上面這行以及重新安裝都無法正常使用再麻煩跟我說

**Comment by philsend** [comment]
我也有一樣的問題 已經確認過版本是1.0 手動安裝過最新的Gentle Viewer也還是一樣

瀏覽器是Google Chrome最新版本
版本 130.0.6723.92 (正式版本) (64 位元)

**Comment by lyj222382** [comment]
@knowlet 
已經確認有這行代碼。並且把原來的腳本刪除後下載重新安裝，EX上排版還是一樣的問題。
浏览器是Google Chrome
版本 109.0.5414.120（正式版本） （64 位）

**Comment by knowlet** [comment]
@lyj222382 @philsend 我猜可能是我螢幕解析度的關係沒有辦法在我的電腦上重現你們的那個問題，我改了一個 1.1 版本，再麻煩幫我測試看看

**Comment by lyj222382** [comment]
@knowlet 感謝K大，更新1.1版本之後沒有問題了。EX上排版一切正常。另外我的螢幕解析度是3840x2160，可能如你想象是那樣的問題。 差@philsend看下有沒有問題了

**Comment by philsend** [comment]
> @lyj222382 @philsend我猜可能是我螢幕解析度的關係沒有辦法在我的電腦上重置你們的那個問題，我改了一個1.1版本，再麻煩幫我測試看看

非常感謝  我也沒問題了
